export const SET_MAINTAB = 'SET_MAINTAB'
export const GET_SHELFBOOKS_REQUEST = 'GET_SHELFBOOKS_REQUEST'
export const GET_SHELFBOOKS_SUCCESS = 'GET_SHELFBOOKS_SUCCESS'
export const GET_SHELFBOOKS_FAILURE = 'GET_SHELFBOOKS_FAILURE'